#pragma once
#include "problem/zdt/zdt.h"
#include "problem/dcdtlz/dcdtlz.h"
#include "problem/dtlz/dtlz.h"
#include "problem/uf/uf.h"
#include "problem/wfg/wfg.h"
#include "problem/lsmop/lsmop.h"
#include "problem/bt/bt.h"
#include "problem/moeadde_f/moeadde_f.h"
#include "problem/immoea_f/immoea_f.h"
#include "problem/moeadm2m_f/moeadm2m_f.h"

#include "problem/sphere/sphere.h"
#include "problem/ackley/ackley.h"
#include "problem/rastrigin/rastrigin.h"
#include "problem/griewank/griewank.h"
#include "problem/kp/knapsack.h"
#include "problem/tsp/tsp.h"
