#pragma once
#include "problem/zdt.h"
#include "problem/dtlz.h"
#include "problem/uf.h"
#include "problem/wfg.h"
#include "problem/lsmop.h"
#include "problem/bt.h"
#include "problem/moeadde_f.h"
#include "problem/immoea_f.h"