#pragma once
#define EMOC_INF 1.0e9
#define EMOC_EPS 1.0e-6
#define PI 3.14159265358979323846
#define MAX_THREAD_NUM 128
#define MAX_BUFFSIZE 256
#define GNUPLOT_TERMINAL "wxt"


#define EMOC_ALGORITHM_REGISTER(CATEGORY,NAME) \
IMPLEMENTED_ALGORITHMS[#CATEGORY].push_back(#NAME);

#define EMOC_PROBLEM_REGISTER(CATEGORY,NAME)\
IMPLEMENTED_PROBLEMS[#CATEGORY].push_back(#NAME);